<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:property name="pi" value="3.1415939331054688" />
  <xacro:property name="front_x" value="0.6964254379272461" />
  <xacro:property name="back_x" value="-0.34882116317749023" />
  <xacro:property name="def_y" value="0.5033063888549805"/>
  <xacro:property name="def_z" value="-0.2631499767303467"/>
  <!--
  <xacro:property name="def_z" value="0.1422966718673706"/>
  -->
  <xacro:macro name="donkey_chains_macro" params="suffix *origin dir">
      
    <link name="chains_loose_${suffix}">
        <visual>
            <geometry>
                <mesh filename="package://iai_sherpa_donkey/meshes/Loose_Wheel.dae"/>
            </geometry>
        </visual>
        <collision>
            <geometry>
                <mesh filename="package://iai_sherpa_donkey/meshes/Loose_Wheel_Col.dae"/>
            </geometry>
        </collision>
        <inertial>
            <origin xyz="0 0 0" rpy="0 0 0"/>
	    <mass value="0.5"/>
            <inertia 
                ixx="0.0001" ixy="0.0" ixz="0.0" 
                iyy="0.0001" iyz="0.0" 
                izz="0.0001"/>
        </inertial>
    </link>
    <joint name="chains_joint_${suffix}" type="revolute">
        <parent link="base_link"/>
        <child link="chains_loose_${suffix}"/>
        <xacro:insert_block name="origin" />
        <limit effort="-1" velocity="-1" upper="2." lower="1."/>
        
        <axis xyz="0 ${dir} 0"/>
    </joint>   
    <transmission name="chain_trans_${suffix}">
        <type>position_controllers/JointTrajectoryController</type>
        <joint name="chains_joint_${suffix}">
            <hardwareInterface>PositionJointInterface</hardwareInterface>
	</joint>
        <actuator name="chain_motor_${suffix}">
            <hardwareInterface>PositionJointInterface</hardwareInterface>
         <mechanicalReduction>10</mechanicalReduction>
       </actuator>
    </transmission>
  </xacro:macro>
  
  <xacro:macro name="donkey_all_chains_macro">
    <xacro:donkey_chains_macro suffix="front_left" dir="1">
        <origin xyz="${front_x} ${def_y} ${def_z}" rpy="${pi} 0 0" />
    </xacro:donkey_chains_macro>
    <xacro:donkey_chains_macro suffix="front_right" dir="-1">
        <origin xyz="${front_x} ${-1 * def_y} ${def_z}" rpy="0.0 0.0 0.0" />
    </xacro:donkey_chains_macro>
    
    <xacro:donkey_chains_macro suffix="back_left" dir="-1">
        <origin xyz="${back_x} ${def_y} ${def_z}" rpy="${pi} ${pi} 0.0" />
    </xacro:donkey_chains_macro>
    <xacro:donkey_chains_macro suffix="back_right" dir="1">
        <origin xyz="${back_x} ${-1 * def_y} ${def_z}" rpy="0.0 ${pi} 0.0" />
    </xacro:donkey_chains_macro>
  </xacro:macro>
</robot>
  